const CONSTANTS = {
  API: "http://localhost:8080/",
  ERROR: {    
    EMAIL: "Please enter valid Email Address.",  
    EMPTY: "Please enter ",
    NAME: "Please enter valid ",  
    PHONE: "Please enter valid Phone Number.",  
    EQUALS_PASSWORD: "New Password and Confirm Password should be same.",
    CLIENT_NAME: "Please Select Client Name",
    GROUP_NAME: "Please Select Group Name",
    SKILL_CATEGORY: "Please Select Competency",
    INTERVIEW_DATE: "Please Select Interview Date",
    INTERVIEW_TIME: "Please Enter Interview Time",
    MODE_OF_INTERVIEW: "Please Select Mode Of Interview",
    DELIVERY_POC_NAME: "Please Enter Delivery Poc Name",
    MOBILE_NUMBER: "Please Enter Client Poc Mobile Number",
    DELIVERY_POC_NUMBER: "Please Enter Delivery Poc Mobile Number",
    INTERVIEW_VENU: "Please Enter Interview Venue",
    COMMENTS: "Please Enter Comments",
    JOB_DESCRIPTION: "Please Enter Job Description",
    CLIENT_POC_NAME: "Please Enter Client Poc Name",
    TO_EMAILS: "Please Enter To Emails",
    CC_EMAILS: "Please Enter CC Emails",
    BCC_EMAILS: "Please Enter BCC Emails",
    PDL_EMAILS: "Please Enter PDL Emails",
    SUCESS: " Schedule Interview is Successful!",
    EROOR: "Schedule Interview is Not Successful!",
    INTERVIEWDATWTIME: "Please Enter Interview Date & Time",
    PASSWORD: "Invalid Password. Try Alphanumeric password with range between 6-15 characters",
    APIERROR: "Unexpected Error has been Occured."
  },
  SENT_REMINDER : "Sent Reminder",
  PENDING  : "Pending for feedback",
  SUBMITED : "Feedback Submitted"
};
export default CONSTANTS;
