const TYPES = {
  UPCOMING: "UPCOMING",
  DASHBOARD: "DASHBOARD",
  PAST_INTERVIEW: "PAST_INTERVIEW",
  USER_LOGOUT: "USER_LOGOUT",
  SPINNER: "SPINNER",
  ERROR: "ERROR",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  ASSOCIATE: "ASSOCIATE",
  GENERAL: "GENERAL",
  GETSKILL: "GETSKILL",
  USERS: "USERS",
  SKILLS: "SKILLS",
  CLIENTS: "CLIENTS",
  NOTIFICATIONS: "NOTIFICATIONS",
  CLIENTGROUPS: "CLIENTGROUPS",
  INTERVIEW_QUE: "INTERVIEW_QUE",
  ASSOCIATEDASHBOARD: "ASSOCIATEDASHBOARD",
  QUESTION: "QUESTION",
  CHANGEUSER: "CHANGEUSER"
};
export default TYPES;
